Repository benbarth/hacktoberfest-swag, pull requests merged in 2020-10, with the labels that each got.

#135 Update info about Circle CI challenges in README.md
  README.md
Labels: good first issue, hacktoberfest

#146 Verified operation code.
  participants/2020/operationcode.yml
Labels: enhancement, hacktoberfest

#154 Added Commercejs
  participants/2020/commercejs.yml
Labels: enhancement, hacktoberfest

#155 Added Mattermost.
  participants/2020/mattermost.yml
Labels: enhancement, hacktoberfest

#156 Added tripal.
  participants/2020/tripal.yml
Labels: enhancement, hacktoberfest

#157 Added specflow.
  participants/2020/specflow.yml
Labels: enhancement, hacktoberfest

#159 add zup
  participants/2020/zup.yml
Labels: enhancement, hacktoberfest-accepted

#169 Added LoginRadius Swags
  participants/2020/loginradius.yml
Labels: enhancement, good first issue, hacktoberfest-accepted
